services:
    hephaestus:
        hostname: 'forge'
        volumes:
            - '.:/home/${APP_PHP_SUPERVISOR_USER}/hephaestus'
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                APP_TIMEZONE: $APP_TIMEZONE
                APP_PHP_SUPERVISOR_USER: $APP_PHP_SUPERVISOR_USER
        env_file:
            - .env
        tty: true
        entrypoint:
          - "/bin/bash"
        ports:
        - 8080:8080
        networks:
            - hephaestus-network
networks:
    hephaestus-network:
        driver: bridge
